//! Generates Rust code from the Control API protos into src/generated.
//! Run via: make generate (from repo root).

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = "src/generated";
    std::fs::create_dir_all(out_dir)?;

    tonic_build::configure()
        .build_server(false)
        .build_client(true)
        .out_dir(out_dir)
        .compile_protos(&["proto/moby/buildkit/v1/control.proto"], &["proto"])?;

    // Tonic names the file from the package: moby.buildkit.v1 -> moby.buildkit.v1.rs
    // Add mod.rs so the main crate can use `mod generated`.
    let mod_rs = r#"// Generated by `make generate`. Do not edit.
include!("moby.buildkit.v1.rs");
"#;
    std::fs::write(std::path::Path::new(out_dir).join("mod.rs"), mod_rs)?;

    println!("Proto code generated in {}", out_dir);
    Ok(())
}
