//! Generates Rust code from the Control API protos into src/generated.
//! Run via: make generate (from repo root).

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let out_dir = "src/generated";
    std::fs::create_dir_all(out_dir)?;
    for entry in std::fs::read_dir(out_dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|ext| ext == "rs") {
            std::fs::remove_file(path)?;
        }
    }

    let protos = [
        "proto/github.com/moby/buildkit/api/services/control/control.proto",
        "proto/github.com/moby/buildkit/api/types/worker.proto",
        "proto/github.com/moby/buildkit/solver/pb/ops.proto",
        "proto/github.com/moby/buildkit/sourcepolicy/pb/policy.proto",
        "proto/google/rpc/status.proto",
    ];

    tonic_build::configure()
        .build_server(false)
        .build_client(true)
        .out_dir(out_dir)
        .compile_protos(&protos, &["proto"])?;

    let mod_rs = r#"// Generated by `make generate`. Do not edit.
pub mod google {
    pub mod rpc {
        include!("google.rpc.rs");
    }
}

pub mod pb {
    include!("pb.rs");
}

pub mod moby {
    pub mod buildkit {
        pub mod v1 {
            pub mod sourcepolicy {
                include!("moby.buildkit.v1.sourcepolicy.rs");
            }

            pub mod types {
                include!("moby.buildkit.v1.types.rs");
            }

            include!("moby.buildkit.v1.rs");
        }
    }
}

pub use moby::buildkit::v1::*;
"#;
    std::fs::write(std::path::Path::new(out_dir).join("mod.rs"), mod_rs)?;

    println!("Proto code generated in {}", out_dir);
    Ok(())
}
