#!/bin/sh
set -eu

: "${BUILDKIT_REF:=v0.31.1}"
: "${BUILDKIT_RAW_BASE:=https://raw.githubusercontent.com/moby/buildkit/${BUILDKIT_REF}}"

if ! command -v curl >/dev/null 2>&1; then
  echo "curl not found in PATH" >&2
  exit 1
fi

repo_root="$(CDPATH= cd "$(dirname "$0")/.." && pwd)"
tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT INT HUP TERM

control_src="$tmp_dir/control.proto"
worker_src="$tmp_dir/worker.proto"

fetch() {
  path="$1"
  out="$2"
  url="${BUILDKIT_RAW_BASE}/${path}"
  printf 'Fetching %s\n' "$url"
  curl -fsSL "$url" -o "$out"
}

require_in_file() {
  file="$1"
  needle="$2"
  if ! grep -Fq "$needle" "$file"; then
    echo "Expected upstream proto to contain: $needle" >&2
    echo "Source file: $file" >&2
    exit 1
  fi
}

fetch "api/services/control/control.proto" "$control_src"
fetch "api/types/worker.proto" "$worker_src"

require_in_file "$control_src" "rpc Info(InfoRequest) returns (InfoResponse);"
require_in_file "$control_src" "rpc ListWorkers(ListWorkersRequest) returns (ListWorkersResponse);"
require_in_file "$control_src" "rpc DiskUsage(DiskUsageRequest) returns (DiskUsageResponse);"
require_in_file "$control_src" "rpc ListenBuildHistory(BuildHistoryRequest) returns (stream BuildHistoryEvent);"
require_in_file "$control_src" "message UsageRecord"
require_in_file "$control_src" "google.rpc.Status error = 5;"
require_in_file "$control_src" "int32 numCachedSteps = 15;"
require_in_file "$control_src" "int32 numTotalSteps = 16;"
require_in_file "$control_src" "int32 numCompletedSteps = 17;"
require_in_file "$worker_src" "message WorkerRecord"
require_in_file "$worker_src" "repeated CDIDevice CDIDevices = 6;"
require_in_file "$worker_src" "string dockerfileVersion = 4;"

proto_dir="$repo_root/proto/moby/buildkit/v1"
mkdir -p "$proto_dir"

cat > "$proto_dir/control.proto" <<EOF
// Minimal BuildKit Control API snapshot from moby/buildkit ${BUILDKIT_REF}.
// Generated by tools/update-protos.sh; run make generate after updating.

syntax = "proto3";

package moby.buildkit.v1;

import "google/protobuf/timestamp.proto";

// Minimal Control service for status/metrics: info, workers, cache (disk usage).
// Wire-compatible with BuildKit's Control API.
// Types inlined so codegen produces a single source file.
service Control {
  rpc Info(InfoRequest) returns (InfoResponse);
  rpc ListWorkers(ListWorkersRequest) returns (ListWorkersResponse);
  rpc DiskUsage(DiskUsageRequest) returns (DiskUsageResponse);
  rpc ListenBuildHistory(BuildHistoryRequest) returns (stream BuildHistoryEvent);
}

// Types wire-compatible with BuildKit api/types/worker.proto.
message Platform {
  string Architecture = 1;
  string OS = 2;
  string Variant = 3;
  string OSVersion = 4;
  repeated string OSFeatures = 5;
}

message BuildkitVersion {
  string package = 1;
  string version = 2;
  string revision = 3;
  string dockerfileVersion = 4;
}

message GCPolicy {
  bool all = 1;
  int64 keepDuration = 2;
  int64 reservedSpace = 3;
  repeated string filters = 4;
  int64 maxUsedSpace = 5;
  int64 minFreeSpace = 6;
}

message CDIDevice {
  string Name = 1;
  bool AutoAllow = 2;
  map<string, string> Annotations = 3;
  bool OnDemand = 4;
}

message WorkerRecord {
  string ID = 1;
  map<string, string> Labels = 2;
  repeated Platform platforms = 3;
  repeated GCPolicy GCPolicy = 4;
  BuildkitVersion BuildkitVersion = 5;
  repeated CDIDevice CDIDevices = 6;
}

// Control messages.
message InfoRequest {}

message InfoResponse {
  BuildkitVersion buildkit_version = 1;
}

message ListWorkersRequest {
  repeated string filter = 1;
}

message ListWorkersResponse {
  repeated WorkerRecord record = 1;
}

message DiskUsageRequest {
  repeated string filter = 1;
  int64 age_limit = 2;
}

message DiskUsageResponse {
  repeated UsageRecord record = 1;
}

message UsageRecord {
  string ID = 1;
  bool Mutable = 2;
  bool InUse = 3;
  int64 Size = 4;
  string Parent = 5 [deprecated = true];
  google.protobuf.Timestamp CreatedAt = 6;
  google.protobuf.Timestamp LastUsedAt = 7;
  int64 UsageCount = 8;
  string Description = 9;
  string RecordType = 10;
  bool Shared = 11;
  repeated string Parents = 12;
}

message BuildHistoryRequest {
  bool ActiveOnly = 1;
  string Ref = 2;
  // EarlyExit: stream existing history then close (no tail).
  bool EarlyExit = 3;
  repeated string Filter = 4;
  int32 Limit = 5;
}

enum BuildHistoryEventType {
  STARTED = 0;
  COMPLETE = 1;
  DELETED = 2;
}

message BuildHistoryEvent {
  BuildHistoryEventType type = 1;
  BuildHistoryRecord record = 2;
}

// Subset of BuildKit's BuildHistoryRecord, with fields used for metrics.
// Field numbers are wire-compatible with the upstream proto.
message BuildHistoryRecord {
  string Ref = 1;
  string Frontend = 2;
  // fields 3-4 (FrontendAttrs, Exporters) skipped
  BuildError error = 5;
  google.protobuf.Timestamp CreatedAt = 6;
  google.protobuf.Timestamp CompletedAt = 7;
  // fields 8-14 skipped
  int32 numCachedSteps = 15;
  int32 numTotalSteps = 16;
  int32 numCompletedSteps = 17;
}

// Wire-compatible with google.rpc.Status (same field numbers).
message BuildError {
  int32 code = 1;
  string message = 2;
}
EOF

cat > "$proto_dir/types.proto" <<EOF
// Minimal BuildKit worker type snapshot from moby/buildkit ${BUILDKIT_REF}.
// Generated by tools/update-protos.sh; run make generate after updating.

syntax = "proto3";

package moby.buildkit.v1.types;

// Minimal types for Control API (Info, ListWorkers). Wire-compatible with BuildKit.

message Platform {
  string Architecture = 1;
  string OS = 2;
  string Variant = 3;
  string OSVersion = 4;
  repeated string OSFeatures = 5;
}

message BuildkitVersion {
  string package = 1;
  string version = 2;
  string revision = 3;
  string dockerfileVersion = 4;
}

message GCPolicy {
  bool all = 1;
  int64 keepDuration = 2;
  int64 reservedSpace = 3;
  repeated string filters = 4;
  int64 maxUsedSpace = 5;
  int64 minFreeSpace = 6;
}

message CDIDevice {
  string Name = 1;
  bool AutoAllow = 2;
  map<string, string> Annotations = 3;
  bool OnDemand = 4;
}

message WorkerRecord {
  string ID = 1;
  map<string, string> Labels = 2;
  repeated Platform platforms = 3;
  repeated GCPolicy GCPolicy = 4;
  BuildkitVersion BuildkitVersion = 5;
  repeated CDIDevice CDIDevices = 6;
}
EOF

printf 'Updated proto snapshot from BuildKit %s\n' "$BUILDKIT_REF"
