---
name: On Release

on:
  release:
    types:
      - published

jobs:
  build-and-push:
    uses: builderhub/actions/.github/workflows/buildah-build-push-workflow.yaml@v0.1.0-beta
    with:
      image: builderhub/buildkit-metrics-agent
      tags: latest ${{ github.sha }} ${{ github.event.release.tag_name }}
      containerfiles: ./Dockerfile
      context: .
      registry: ghcr.io
      push: true
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: write
